In [2]:
# This is a anndata tutorial Python script.
# Press ⌃R to execute it or replace it with your code.

import numpy as np
import pandas as pd
import anndata as ad
from scipy.sparse import csr_matrix
from importlib.metadata import version
from IPython.display import display
version("anndata")

'0.12.19'

In [4]:
def print_hi(name):
    print(f'Hi, {name}')  # Press ⌘F8 to toggle the breakpoint.

if __name__ == '__main__':
    print_hi('PyCharm')

Hi, PyCharm

In [6]:
counts = csr_matrix(np.random.poisson(1, size=(100, 2000)), dtype=np.float32)
adata = ad.AnnData(counts)
print("adata: ", adata)
print("adata.X: ", adata.X)

adata:  AnnData object with n_obs × n_vars = 100 × 2000
adata.X:  <Compressed Sparse Row sparse matrix of dtype 'float32'
	with 126156 stored elements and shape (100, 2000)>
  Coords	Values
  (0, 0)	1.0
  (0, 1)	2.0
  (0, 2)	1.0
  (0, 3)	4.0
  (0, 6)	1.0
  (0, 7)	1.0
  (0, 8)	4.0
  (0, 10)	1.0
  (0, 11)	1.0
  (0, 12)	3.0
  (0, 16)	1.0
  (0, 17)	1.0
  (0, 20)	1.0
  (0, 21)	2.0
  (0, 26)	2.0
  (0, 27)	2.0
  (0, 28)	1.0
  (0, 29)	1.0
  (0, 30)	1.0
  (0, 31)	1.0
  (0, 34)	2.0
  (0, 36)	1.0
  (0, 38)	1.0
  (0, 40)	2.0
  (0, 41)	1.0
  :	:
  (99, 1963)	2.0
  (99, 1965)	1.0
  (99, 1966)	2.0
  (99, 1967)	2.0
  (99, 1968)	1.0
  (99, 1970)	1.0
  (99, 1971)	1.0
  (99, 1972)	1.0
  (99, 1973)	1.0
  (99, 1975)	1.0
  (99, 1976)	1.0
  (99, 1980)	1.0
  (99, 1981)	1.0
  (99, 1983)	1.0
  (99, 1985)	1.0
  (99, 1986)	1.0
  (99, 1987)	1.0
  (99, 1988)	1.0
  (99, 1992)	1.0
  (99, 1993)	1.0
  (99, 1994)	1.0
  (99, 1996)	1.0
  (99, 1997)	4.0
  (99, 1998)	3.0
  (99, 1999)	2.0

In [7]:
adata.obs_names = [f"Cell_{i:d}" for i in range(adata.n_obs)]
adata.var_names = [f"Gene_{i:d}" for i in range(adata.n_vars)]
print(adata.obs_names[:10])
print(adata.var_names[:10])

print("subset:" , adata[["Cell_1", "Cell_10"], ["Gene_1", "Gene_20", "Gene_1981"]])

Index(['Cell_0', 'Cell_1', 'Cell_2', 'Cell_3', 'Cell_4', 'Cell_5', 'Cell_6',
       'Cell_7', 'Cell_8', 'Cell_9'],
      dtype='object')
Index(['Gene_0', 'Gene_1', 'Gene_2', 'Gene_3', 'Gene_4', 'Gene_5', 'Gene_6',
       'Gene_7', 'Gene_8', 'Gene_9'],
      dtype='object')
subset: View of AnnData object with n_obs × n_vars = 2 × 3

In [9]:
ct = np.random.choice(["B", "T", "Monocyte"], size = (adata.n_obs))
adata.obs["Cell_type"] = pd.Categorical(ct)
display(adata.obs)

        Cell_type
Cell_0          T
Cell_1   Monocyte
Cell_2          T
Cell_3          T
Cell_4          T
...           ...
Cell_95         B
Cell_96  Monocyte
Cell_97         T
Cell_98         T
Cell_99  Monocyte

[100 rows x 1 columns]

In [11]:
display(adata)
print(adata)

AnnData object with n_obs × n_vars = 100 × 2000
    obs: 'Cell_type'

AnnData object with n_obs × n_vars = 100 × 2000
    obs: 'Cell_type'

In [16]:
print("n_obs: ", adata.n_obs)
print("n_vars: ", adata.n_vars)
gene_types = np.random.choice(["intron", "exon", "promotor"], size=adata.n_vars)
adata.var["gene_type"] = pd.Categorical(gene_types)
display(adata)
display(adata.var)

n_obs:  100
n_vars:  2000

AnnData object with n_obs × n_vars = 100 × 2000
    obs: 'Cell_type'
    var: 'gene_type'

          gene_type
Gene_0         exon
Gene_1       intron
Gene_2         exon
Gene_3     promotor
Gene_4     promotor
...             ...
Gene_1995    intron
Gene_1996  promotor
Gene_1997    intron
Gene_1998    intron
Gene_1999      exon

[2000 rows x 1 columns]

In [21]:
adata.obsm["X_umap"] = np.random.normal(0, 1, size=(adata.n_obs, 2))
adata.varm["gene_stuff"] = np.random.normal(0, 1, size=(adata.n_vars, 5))

print(adata)

print(adata.obsm["X_umap"][:5])

AnnData object with n_obs × n_vars = 100 × 2000
    obs: 'Cell_type'
    var: 'gene_type'
    obsm: 'X_umap'
    varm: 'gene_stuff'
[[ 0.65744151  0.66485872]
 [ 0.50791157  0.41298781]
 [ 2.04606831 -1.23764072]
 [ 0.76453194  0.41737819]
 [ 0.94123545 -2.04280455]]